name: build
on:
  workflow_call:
    inputs:
      py-version:
        required: true
        type: string
jobs:
  tests:
    runs-on: ubuntu-latest
    name: unit tests py ${{ inputs.py-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.py-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.py-version }}
      - name: Install dependencies
        run: pip install tox codecov
      - name: Set TOXENV
        run: |
          python_version="${{ inputs.py-version }}"
          py_version="${python_version/./}"
          target_branch=${{ github.base_ref || github.ref }}
          target_branch=(`[[ ${target_branch::10} == 'refs/heads' ]] && echo ${target_branch:11} || echo $target_branch`)
          echo "target_branch =" $target_branch
          is_master=(`[[ $target_branch == 'master' ]] && echo 'true' || echo 'false'`)
          is_tag=${{ startsWith(github.ref, 'refs/tags') }}
          echo "is_master =" $is_master
          echo "is_tag =" $is_tag
          branch=(`[[ $is_master == 'true' || $is_tag == 'true' ]] && echo 'master' || echo 'dev'`)
          TOXENV="py$py_version-$branch"
          echo $TOXENV
          echo "TOXENV=$TOXENV" >> $GITHUB_ENV
      - name: Run tox
        run: tox
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
